driver: oracle.jdbc.driver.OracleDriver
url: jdbc:oracle:thin:@localhost:1521:XE
dbuser: system
dbpassword: system
server.servlet.contextPath: /ajaxProject
spring.security.user.name: pawanKumar
spring.security.user.password: Abcd12345
